#!/bin/bash

# Sanctum Sudo Setup Script
# This script configures passwordless sudo for specific commands needed by Sanctum

set -e

echo "======================================"
echo "Sanctum Sudo Permission Setup"
echo "======================================"
echo ""
echo "This script will configure passwordless sudo for specific commands"
echo "that Sanctum needs to manage WordPress sites effectively."
echo ""
echo "Commands that will be allowed without password:"
echo "- rm, cp, mv, chown, chmod (for site file management)"
echo "- Commands only within /home/$USER/sanctum/sites/"
echo ""
echo "This is more secure than full passwordless sudo access."
echo ""

# Check if running as root
if [ "$EUID" -eq 0 ]; then 
   echo "Error: Please run this script as your regular user, not as root."
   exit 1
fi

# Get the current user
CURRENT_USER=$(whoami)
SANCTUM_DIR="/home/$CURRENT_USER/sanctum"

echo "Setting up sudo permissions for user: $CURRENT_USER"
echo "Sanctum directory: $SANCTUM_DIR"
echo ""

# Ask for confirmation
read -p "Do you want to continue? (y/N) " -n 1 -r
echo
if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    echo "Setup cancelled."
    exit 1
fi

# Create sudoers file content
SUDOERS_FILE="/etc/sudoers.d/sanctum-$CURRENT_USER"
SUDOERS_CONTENT="# Sanctum WordPress Manager - Passwordless sudo for specific commands
# Generated by setup-sudo.sh

# Allow file operations within sanctum sites directory
$CURRENT_USER ALL=(ALL) NOPASSWD: /bin/rm -rf $SANCTUM_DIR/sites/*
$CURRENT_USER ALL=(ALL) NOPASSWD: /bin/cp -r * $SANCTUM_DIR/sites/*
$CURRENT_USER ALL=(ALL) NOPASSWD: /bin/mv * $SANCTUM_DIR/sites/*
$CURRENT_USER ALL=(ALL) NOPASSWD: /bin/chown -R * $SANCTUM_DIR/sites/*
$CURRENT_USER ALL=(ALL) NOPASSWD: /bin/chmod -R * $SANCTUM_DIR/sites/*
$CURRENT_USER ALL=(ALL) NOPASSWD: /usr/bin/find $SANCTUM_DIR/sites/* *

# Allow operations on hosts file for domain management
$CURRENT_USER ALL=(ALL) NOPASSWD: /usr/bin/tee -a /etc/hosts
$CURRENT_USER ALL=(ALL) NOPASSWD: /bin/sed -i * /etc/hosts

# Allow nginx reload for proxy management
$CURRENT_USER ALL=(ALL) NOPASSWD: /usr/sbin/nginx -s reload
$CURRENT_USER ALL=(ALL) NOPASSWD: /usr/sbin/nginx -t

# Allow Docker operations (if needed)
$CURRENT_USER ALL=(ALL) NOPASSWD: /usr/bin/docker *
"

echo ""
echo "The following sudoers configuration will be created:"
echo "----------------------------------------"
echo "$SUDOERS_CONTENT"
echo "----------------------------------------"
echo ""
echo "This configuration will be saved to: $SUDOERS_FILE"
echo ""
echo "You will be prompted for your password to create this file."
echo ""

# Create temporary file
TEMP_FILE=$(mktemp)
echo "$SUDOERS_CONTENT" > "$TEMP_FILE"

# Validate the sudoers file
if sudo visudo -c -f "$TEMP_FILE"; then
    echo "Sudoers configuration is valid."
    
    # Install the sudoers file
    sudo cp "$TEMP_FILE" "$SUDOERS_FILE"
    sudo chmod 440 "$SUDOERS_FILE"
    
    echo ""
    echo "✓ Sudo permissions configured successfully!"
    echo ""
    echo "Testing sudo access..."
    
    # Test sudo access
    if sudo -n true 2>/dev/null; then
        echo "✓ Passwordless sudo is working!"
    else
        echo "⚠ Passwordless sudo test failed. You may need to log out and back in."
    fi
    
    # Clean up
    rm -f "$TEMP_FILE"
    
    echo ""
    echo "======================================"
    echo "Setup Complete!"
    echo "======================================"
    echo ""
    echo "Sanctum can now perform file operations without password prompts."
    echo ""
    echo "If you encounter any issues:"
    echo "1. Try logging out and back in"
    echo "2. Check the sudoers file: sudo cat $SUDOERS_FILE"
    echo "3. Remove if needed: sudo rm $SUDOERS_FILE"
    echo ""
else
    echo "Error: Invalid sudoers configuration!"
    rm -f "$TEMP_FILE"
    exit 1
fi