#!/bin/bash
# Script to ensure mkcert is properly set up for Sanctum

echo "Sanctum mkcert Setup"
echo "===================="
echo

# Colors for output
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

# Check if mkcert is installed
if ! command -v mkcert &> /dev/null; then
  echo -e "${RED}mkcert is not installed!${NC}"
  echo
  echo "Please install mkcert first:"
  echo "  - Ubuntu/Debian: sudo apt install mkcert"
  echo "  - Or download from: https://github.com/FiloSottile/mkcert/releases"
  exit 1
fi

echo -e "${GREEN}✓ mkcert is installed${NC}"
echo

# Check if CA is installed
echo "Checking if mkcert CA is installed..."
if mkcert -install 2>&1 | grep -q "is already installed"; then
  echo -e "${GREEN}✓ mkcert CA is already installed${NC}"
else
  echo -e "${YELLOW}Installing mkcert CA...${NC}"
  mkcert -install
  if [ $? -eq 0 ]; then
    echo -e "${GREEN}✓ mkcert CA installed successfully${NC}"
  else
    echo -e "${RED}✗ Failed to install mkcert CA${NC}"
    exit 1
  fi
fi

echo
echo "mkcert CA location:"
mkcert -CAROOT

echo
echo -e "${GREEN}Setup complete!${NC}"
echo
echo "The mkcert Certificate Authority is now trusted by:"
echo "  - System certificate store"
echo "  - Chrome/Chromium"
echo "  - Firefox"
echo "  - Other applications using system certificates"
echo
echo "All certificates generated by Sanctum will now be automatically trusted."
echo
echo "Note: If you're still seeing certificate warnings:"
echo "  1. Try restarting your browser"
echo "  2. Clear browser cache"
echo "  3. For Firefox, you may need to manually trust the CA"