import { execSync, spawn } from 'child_process';
import readline from 'readline';
import { logger } from '../middleware/logging.js';
import path from 'path';
import fs from 'fs-extra';

class SSLTrustHelper {
  constructor() {
    this.rl = null;
  }

  /**
   * Create readline interface for user input
   */
  createInterface() {
    if (!this.rl) {
      this.rl = readline.createInterface({
        input: process.stdin,
        output: process.stdout
      });
    }
    return this.rl;
  }

  /**
   * Close readline interface
   */
  closeInterface() {
    if (this.rl) {
      this.rl.close();
      this.rl = null;
    }
  }

  /**
   * Ask user a yes/no question
   */
  async askYesNo(question) {
    return new Promise((resolve) => {
      const rl = this.createInterface();
      rl.question(`${question} (y/N): `, (answer) => {
        resolve(answer.toLowerCase() === 'y' || answer.toLowerCase() === 'yes');
      });
    });
  }

  /**
   * Prompt user to trust SSL certificate
   */
  async promptForSSLTrust(domain) {
    try {
      console.log('\n' + '='.repeat(60));
      console.log('SSL CERTIFICATE TRUST');
      console.log('='.repeat(60));
      console.log(`\nThe SSL certificate for ${domain} has been generated.`);
      console.log('To avoid browser warnings, the certificate needs to be trusted.\n');
      
      // Check if mkcert CA is installed
      const isMkcertCAInstalled = await this.checkMkcertCA();
      
      if (!isMkcertCAInstalled) {
        console.log('⚠️  mkcert CA is not installed!');
        console.log('   Installing the mkcert CA will trust ALL certificates generated by Sanctum.\n');
        
        const installCA = await this.askYesNo('Would you like to install the mkcert CA now? (recommended)');
        
        if (installCA) {
          await this.installMkcertCA();
          console.log('\n✓ mkcert CA installed successfully!');
          console.log('  All Sanctum certificates are now trusted.\n');
          this.closeInterface();
          return true;
        }
      }
      
      // If CA is installed but certificate still not trusted, try manual trust
      console.log(`\nWould you like to trust the certificate for ${domain}?`);
      console.log('This requires sudo access.\n');
      
      const trustNow = await this.askYesNo('Trust this certificate now?');
      
      if (trustNow) {
        console.log('\nTrusting certificate (you may be prompted for sudo password)...\n');
        await this.trustCertificate(domain);
        console.log('\n✓ Certificate trusted successfully!');
      } else {
        console.log('\n⚠️  Certificate not trusted.');
        console.log(`   You can trust it later by running:`);
        console.log(`   ./trust-site-certificate.sh ${domain}\n`);
      }
      
      this.closeInterface();
      return trustNow;
      
    } catch (error) {
      logger.error(`Error in SSL trust prompt: ${error.message}`);
      this.closeInterface();
      return false;
    }
  }

  /**
   * Check if mkcert CA is installed
   */
  async checkMkcertCA() {
    try {
      const result = execSync('mkcert -install 2>&1', { encoding: 'utf8' });
      return result.includes('is already installed');
    } catch (error) {
      return false;
    }
  }

  /**
   * Install mkcert CA
   */
  async installMkcertCA() {
    return new Promise((resolve, reject) => {
      console.log('Installing mkcert CA...');
      
      const proc = spawn('mkcert', ['-install'], {
        stdio: 'inherit',
        shell: true
      });
      
      proc.on('close', (code) => {
        if (code === 0) {
          resolve();
        } else {
          reject(new Error(`mkcert CA installation failed with code ${code}`));
        }
      });
      
      proc.on('error', (error) => {
        reject(error);
      });
    });
  }

  /**
   * Trust a specific certificate
   */
  async trustCertificate(domain) {
    const sanctumHome = process.env.SANCTUM_HOME || path.join(process.env.HOME, 'sanctum');
    const scriptPath = path.join(sanctumHome, 'app', 'trust-certificate-single.sh');
    
    return new Promise((resolve, reject) => {
      // Check if script exists
      if (!fs.existsSync(scriptPath)) {
        // Fallback to direct command
        const certPath = path.join(sanctumHome, 'ssl', 'certs', domain, `${domain}.pem`);
        
        const proc = spawn('sudo', [
          'sh', '-c',
          `cp "${certPath}" "/usr/local/share/ca-certificates/sanctum-${domain}.crt" && update-ca-certificates`
        ], {
          stdio: 'inherit'
        });
        
        proc.on('close', (code) => {
          if (code === 0) {
            // Also try to add to Chrome/Chromium
            try {
              this.addToChromeStore(domain, certPath);
            } catch (error) {
              // Non-fatal
            }
            resolve();
          } else {
            reject(new Error(`Certificate trust failed with code ${code}`));
          }
        });
        
        proc.on('error', reject);
      } else {
        // Use the trust script
        const proc = spawn(scriptPath, [domain], {
          stdio: 'inherit'
        });
        
        proc.on('close', (code) => {
          if (code === 0) {
            resolve();
          } else {
            reject(new Error(`Trust script failed with code ${code}`));
          }
        });
        
        proc.on('error', reject);
      }
    });
  }

  /**
   * Add certificate to Chrome/Chromium store
   */
  addToChromeStore(domain, certPath) {
    const nssDbPaths = [
      path.join(process.env.HOME, '.pki', 'nssdb'),
      path.join(process.env.HOME, 'snap', 'chromium', 'current', '.pki', 'nssdb')
    ];
    
    for (const dbPath of nssDbPaths) {
      if (fs.existsSync(dbPath)) {
        try {
          // Remove existing
          execSync(`certutil -D -n "sanctum-${domain}" -d sql:${dbPath} 2>/dev/null || true`);
          // Add new
          execSync(`certutil -A -n "sanctum-${domain}" -t "C,," -i "${certPath}" -d sql:${dbPath}`);
        } catch (error) {
          // Non-fatal
        }
      }
    }
  }
}

export default new SSLTrustHelper();